openapi: 3.0.4
info:
  title: Subscription log models
  description: Log models for logging services of subscription
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonSubscriptionLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов подписки в системе
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        subscription:
          $ref: '#/components/schemas/SubscriptionLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/SubscriptionErrorLogModel'

    SubscriptionLogModel:
      title: Модель лога для микросервиса Subscription
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
            - status
            - offers
        requestSubscription:
          $ref: '#/components/schemas/SubscriptionLog'
        requestFilter:
          $ref: '#/components/schemas/SubscriptionFilterLog'
        responseSubscription:
          $ref: '#/components/schemas/SubscriptionLog'
        responseSubscriptions:
          type: array
          items:
            $ref: '#/components/schemas/SubscriptionLog'

    SubscriptionErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    SubscriptionLog:
      title: Модель лога для объявления
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        subscriptionType:
          type: string
        subscriptionStatus:
          type: string
        productId:
          type: string


    SubscriptionFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        statusString:
          type: string
        dealSide:
          type: string